"""empty message

Revision ID: 04fafaa5b488
Revises: 45e63cc20adf
Create Date: 2023-10-02 10:35:24.614730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fafaa5b488'
down_revision = '45e63cc20adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_bolsa_familia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nis', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_condicao_moradia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipoCasa', sa.String(), nullable=False),
    sa.Column('banheiroComFossa', sa.Boolean(), nullable=False),
    sa.Column('aguaCagepa', sa.Boolean(), nullable=False),
    sa.Column('poco', sa.Boolean(), nullable=False),
    sa.Column('energia', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_problema_enfrentado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alcool', sa.Boolean(), nullable=False),
    sa.Column('lazer', sa.Boolean(), nullable=False),
    sa.Column('saude', sa.Boolean(), nullable=False),
    sa.Column('fome', sa.Boolean(), nullable=False),
    sa.Column('drogas', sa.Boolean(), nullable=False),
    sa.Column('violencia', sa.Boolean(), nullable=False),
    sa.Column('desemprego', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_condicao_vida',
    sa.Column('problemaEnfrentado_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trabalhoDaFamilia', sa.String(), nullable=False),
    sa.Column('quantasPessoasTrabalhamNaCasa', sa.Integer(), nullable=False),
    sa.Column('rendaMensalFamilia', sa.String(), nullable=False),
    sa.Column('programaGoverno', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problemaEnfrentado_id'], ['tb_problema_enfrentado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsavel',
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('bolsaFamilia_id', sa.UUID(), nullable=False),
    sa.Column('condicaoMoradia_id', sa.UUID(), nullable=False),
    sa.Column('condicaoVida_id', sa.UUID(), nullable=False),
    sa.Column('parentesco', sa.String(), nullable=False),
    sa.Column('escolaridade', sa.String(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('dataExpedicaoRg', sa.DateTime(), nullable=False),
    sa.Column('ssp', sa.String(), nullable=False),
    sa.Column('dataExpedicaoCpf', sa.DateTime(), nullable=False),
    sa.Column('profissao', sa.String(), nullable=False),
    sa.Column('nomeMae', sa.String(), nullable=False),
    sa.Column('ufRg', sa.String(), nullable=False),
    sa.Column('emissorRg', sa.String(), nullable=False),
    sa.Column('familiaresCasa', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bolsaFamilia_id'], ['tb_bolsa_familia.id'], ),
    sa.ForeignKeyConstraint(['condicaoMoradia_id'], ['tb_condicao_moradia.id'], ),
    sa.ForeignKeyConstraint(['condicaoVida_id'], ['tb_condicao_vida.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('pessoa_id')
    )
    op.create_table('tb_educando_responsavel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('educando_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['educando_id'], ['tb_educando.pessoa_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('tb_educando_responsavel')
    op.drop_table('responsavel')
    op.drop_table('tb_condicao_vida')
    op.drop_table('tb_problema_enfrentado')
    op.drop_table('tb_condicao_moradia')
    op.drop_table('tb_bolsa_familia')
    # ### end Alembic commands ###
