"""empty message

Revision ID: 096d3a80bc1a
Revises: 234137bcf219
Create Date: 2023-10-31 12:55:39.931100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096d3a80bc1a'
down_revision = '234137bcf219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.alter_column('educando_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.alter_column('educando_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
