"""empty message

Revision ID: 1010628ef983
Revises: 18e145ba65a9
Create Date: 2023-10-02 10:44:03.171378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1010628ef983'
down_revision = '18e145ba65a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_responsavel',
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('bolsaFamilia_id', sa.UUID(), nullable=False),
    sa.Column('condicaoMoradia_id', sa.UUID(), nullable=False),
    sa.Column('condicaoVida_id', sa.UUID(), nullable=False),
    sa.Column('parentesco', sa.String(), nullable=False),
    sa.Column('escolaridade', sa.String(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('dataExpedicaoRg', sa.DateTime(), nullable=False),
    sa.Column('ssp', sa.String(), nullable=False),
    sa.Column('dataExpedicaoCpf', sa.DateTime(), nullable=False),
    sa.Column('profissao', sa.String(), nullable=False),
    sa.Column('nomeMae', sa.String(), nullable=False),
    sa.Column('ufRg', sa.String(), nullable=False),
    sa.Column('emissorRg', sa.String(), nullable=False),
    sa.Column('familiaresCasa', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bolsaFamilia_id'], ['tb_bolsa_familia.id'], ),
    sa.ForeignKeyConstraint(['condicaoMoradia_id'], ['tb_condicao_moradia.id'], ),
    sa.ForeignKeyConstraint(['condicaoVida_id'], ['tb_condicao_vida.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('pessoa_id')
    )
    op.drop_table('responsavel')
    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_responsavel', ['responsavel_id'], ['pessoa_id'])

    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('responsavel_id')

    op.create_table('responsavel',
    sa.Column('pessoa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bolsaFamilia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('condicaoMoradia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('condicaoVida_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parentesco', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('escolaridade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('apelido', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataExpedicaoRg', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ssp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataExpedicaoCpf', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('profissao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nomeMae', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ufRg', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emissorRg', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('familiaresCasa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bolsaFamilia_id'], ['tb_bolsa_familia.id'], name='responsavel_bolsaFamilia_id_fkey'),
    sa.ForeignKeyConstraint(['condicaoMoradia_id'], ['tb_condicao_moradia.id'], name='responsavel_condicaoMoradia_id_fkey'),
    sa.ForeignKeyConstraint(['condicaoVida_id'], ['tb_condicao_vida.id'], name='responsavel_condicaoVida_id_fkey'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], name='responsavel_pessoa_id_fkey'),
    sa.PrimaryKeyConstraint('pessoa_id', name='responsavel_pkey')
    )
    op.drop_table('tb_responsavel')
    # ### end Alembic commands ###
