"""empty message

Revision ID: 18e145ba65a9
Revises: b7b9cb97ced8
Create Date: 2023-10-02 10:38:10.477917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e145ba65a9'
down_revision = 'b7b9cb97ced8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao_ensino', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
