"""empty message

Revision ID: 234137bcf219
Revises: cbd8b55eba01
Create Date: 2023-10-31 12:55:06.501095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234137bcf219'
down_revision = 'cbd8b55eba01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.alter_column('educando_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_constraint('tb_relatorio_academico_educando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_educando', ['educando_id'], ['pessoa_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_relatorio_academico_educando_id_fkey', 'tb_educando', ['educando_id'], ['pessoa_id'], ondelete='CASCADE')
        batch_op.alter_column('educando_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
