"""empty message

Revision ID: 2d84ecd87ef6
Revises: 79781f264f57
Create Date: 2023-10-17 20:00:22.717958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d84ecd87ef6'
down_revision = '79781f264f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_condicao_vida', schema=None) as batch_op:
        batch_op.alter_column('problemaEnfrentado_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('tb_condicao_vida_problemaEnfrentado_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_problema_enfrentado', ['problemaEnfrentado_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_observacoesEducando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_responsavel_responsavel_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tb_educando_responsavel_educando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_educando', ['educando_id'], ['pessoa_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tb_responsavel', ['responsavel_id'], ['pessoa_id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint('tb_responsavel_condicaoVida_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tb_responsavel_bolsaFamilia_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tb_responsavel_condicaoMoradia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_condicao_moradia', ['condicaoMoradia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tb_condicao_vida', ['condicaoVida_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tb_bolsa_familia', ['bolsaFamilia_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_responsavel_condicaoMoradia_id_fkey', 'tb_condicao_moradia', ['condicaoMoradia_id'], ['id'])
        batch_op.create_foreign_key('tb_responsavel_bolsaFamilia_id_fkey', 'tb_bolsa_familia', ['bolsaFamilia_id'], ['id'])
        batch_op.create_foreign_key('tb_responsavel_condicaoVida_id_fkey', 'tb_condicao_vida', ['condicaoVida_id'], ['id'])

    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_responsavel_educando_id_fkey', 'tb_educando', ['educando_id'], ['pessoa_id'])
        batch_op.create_foreign_key('tb_educando_responsavel_responsavel_id_fkey', 'tb_responsavel', ['responsavel_id'], ['pessoa_id'])

    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_observacoesEducando_id_fkey', 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'])

    with op.batch_alter_table('tb_condicao_vida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_condicao_vida_problemaEnfrentado_id_fkey', 'tb_problema_enfrentado', ['problemaEnfrentado_id'], ['id'])
        batch_op.alter_column('problemaEnfrentado_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
