"""empty message

Revision ID: 30dfdcbb5233
Revises: 096d3a80bc1a
Create Date: 2023-10-31 13:34:37.671924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dfdcbb5233'
down_revision = '096d3a80bc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataCriacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.drop_column('dataCriacao')

    # ### end Alembic commands ###
