"""empty message

Revision ID: 3419e645689e
Revises: 718367b2a98c
Create Date: 2023-10-18 20:05:29.124873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3419e645689e'
down_revision = '718367b2a98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_responsavel_responsavel_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tb_educando_responsavel_educando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_responsavel', ['responsavel_id'], ['pessoa_id'])
        batch_op.create_foreign_key(None, 'tb_educando', ['educando_id'], ['pessoa_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_responsavel_educando_id_fkey', 'tb_educando', ['educando_id'], ['pessoa_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('tb_educando_responsavel_responsavel_id_fkey', 'tb_responsavel', ['responsavel_id'], ['pessoa_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
