"""empty message

Revision ID: 38b422b69de7
Revises: a5ef50182a07
Create Date: 2023-11-17 08:23:44.354706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b422b69de7'
down_revision = 'a5ef50182a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_instituicao_id_fkey', type_='foreignkey')
        batch_op.drop_column('instituicao_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_educando_instituicao_id_fkey', 'tb_instituicao_ensino', ['instituicao_id'], ['id'])

    # ### end Alembic commands ###
