"""empty message

Revision ID: 50f5bd1a9d09
Revises: b1d9a99d36b9
Create Date: 2023-12-07 11:03:20.258049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f5bd1a9d09'
down_revision = 'b1d9a99d36b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.drop_column('idade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
