"""atualizando tabelas

Revision ID: 53dff8a7c326
Revises: dbd399764abd
Create Date: 2023-09-19 09:53:27.069892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dff8a7c326'
down_revision = 'dbd399764abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.alter_column('dataNascimento',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.alter_column('dataNascimento',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
