"""empty message

Revision ID: 70283c74e96f
Revises: 2d84ecd87ef6
Create Date: 2023-10-17 20:09:15.567136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70283c74e96f'
down_revision = '2d84ecd87ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.alter_column('observacoesEducando_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.alter_column('observacoesEducando_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
