"""empty message

Revision ID: 79781f264f57
Revises: e59fc2d7ef51
Create Date: 2023-10-16 08:30:24.524802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79781f264f57'
down_revision = 'e59fc2d7ef51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_column('ssp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssp', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
