"""empty message

Revision ID: 8207f68cc8ad
Revises: b081ce6d32aa
Create Date: 2023-11-06 10:18:28.189367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8207f68cc8ad'
down_revision = 'b081ce6d32aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.drop_constraint('tb_turma_instituicao_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_instituicao_ensino', ['instituicao_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_turma_instituicao_id_fkey', 'tb_instituicao_ensino', ['instituicao_id'], ['id'])

    # ### end Alembic commands ###
