"""Inicializando tabelas

Revision ID: 843fc5fd64ba
Revises: 
Create Date: 2023-09-19 22:22:47.804142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843fc5fd64ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbEndereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbPessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('rg', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('dataNascimento', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('tbFuncionario',
    sa.Column('pessoaId', sa.Integer(), nullable=False),
    sa.Column('enderecoId', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enderecoId'], ['tbEndereco.id'], ),
    sa.ForeignKeyConstraint(['pessoaId'], ['tbPessoa.id'], ),
    sa.PrimaryKeyConstraint('pessoaId'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbFuncionario')
    op.drop_table('tbPessoa')
    op.drop_table('tbEndereco')
    # ### end Alembic commands ###
