"""empty message

Revision ID: 8d078d0790a5
Revises: 
Create Date: 2023-11-01 09:10:58.488014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d078d0790a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_relatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('educando_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=True),
    sa.Column('relatorio', sa.LargeBinary(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['educando_id'], ['tb_educando.pessoa_id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['tb_funcionario.pessoa_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_relatorio')
    # ### end Alembic commands ###
