"""empty message

Revision ID: 949dc5ec04a0
Revises: 
Create Date: 2023-12-10 19:48:26.768666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949dc5ec04a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_turma_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_turma', ['turma_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_turma_id_fkey', 'tb_turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###
