"""empty message

Revision ID: 94b68058851d
Revises: b0955c44eee1
Create Date: 2023-09-29 14:28:23.699790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b68058851d'
down_revision = 'b0955c44eee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_deficiencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intelectual', sa.Boolean(), nullable=False),
    sa.Column('auditiva', sa.Boolean(), nullable=False),
    sa.Column('visual', sa.Boolean(), nullable=False),
    sa.Column('fisica', sa.Boolean(), nullable=False),
    sa.Column('multipla', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_instituicao_ensino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_turma',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_observacoes_educando',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deficiencia_id', sa.UUID(), nullable=True),
    sa.Column('alimentacao', sa.String(), nullable=False),
    sa.Column('medicacao', sa.String(), nullable=False),
    sa.Column('produtoHigienePessoal', sa.String(), nullable=False),
    sa.Column('tipoSangue', sa.String(), nullable=False),
    sa.Column('medicacaoDeficiencia', sa.String(), nullable=False),
    sa.Column('laudoMedico', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deficiencia_id'], ['tb_deficiencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_educando',
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=True),
    sa.Column('instituicao_id', sa.UUID(), nullable=True),
    sa.Column('observacoesEducando_id', sa.UUID(), nullable=True),
    sa.Column('nis', sa.String(), nullable=False),
    sa.Column('cidadeCartorio', sa.String(), nullable=False),
    sa.Column('sus', sa.String(), nullable=False),
    sa.Column('nomeCartorio', sa.DateTime(), nullable=False),
    sa.Column('numeroRegistroNascimento', sa.String(), nullable=False),
    sa.Column('dataEmissaoCertidao', sa.DateTime(), nullable=False),
    sa.Column('ufCartorio', sa.String(), nullable=False),
    sa.Column('etnia', sa.String(), nullable=False),
    sa.Column('nomeMae', sa.String(), nullable=False),
    sa.Column('nomePai', sa.String(), nullable=False),
    sa.Column('dataMatricula', sa.DateTime(), nullable=True),
    sa.Column('ano', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['tb_instituicao_ensino.id'], ),
    sa.ForeignKeyConstraint(['observacoesEducando_id'], ['tb_observacoes_educando.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['tb_turma.id'], ),
    sa.PrimaryKeyConstraint('pessoa_id')
    )
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataCriacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.drop_column('dataCriacao')

    op.drop_table('tb_educando')
    op.drop_table('tb_observacoes_educando')
    op.drop_table('tb_turma')
    op.drop_table('tb_instituicao_ensino')
    op.drop_table('tb_deficiencia')
    # ### end Alembic commands ###
