"""empty message

Revision ID: 9edb5014d02c
Revises: 05715856bf15
Create Date: 2023-10-17 20:19:09.332819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edb5014d02c'
down_revision = '05715856bf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_observacoesEducando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_observacoesEducando_id_fkey', 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
