"""empty message

Revision ID: a5d5cbd34cdd
Revises: f4d6016cfa0c
Create Date: 2023-10-18 20:15:54.648897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d5cbd34cdd'
down_revision = 'f4d6016cfa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.drop_constraint('tb_pessoa_endereco_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_endereco', ['endereco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_pessoa_endereco_id_fkey', 'tb_endereco', ['endereco_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
