"""empty message

Revision ID: b0189a484f1f
Revises: 
Create Date: 2023-12-10 10:02:35.241889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0189a484f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'tb_relatorio', ['relatorio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('relatorio_id')

    # ### end Alembic commands ###
