"""empty message

Revision ID: b081ce6d32aa
Revises: 6232bd1662c2
Create Date: 2023-11-06 10:03:22.812283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b081ce6d32aa'
down_revision = '6232bd1662c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.alter_column('turno',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_turma', schema=None) as batch_op:
        batch_op.alter_column('turno',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
