"""Inicializando tabelas

Revision ID: b0955c44eee1
Revises: 
Create Date: 2023-09-20 17:05:35.076725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0955c44eee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_endereco',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pessoa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endereco_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sexo', sa.Boolean(), nullable=False),
    sa.Column('rg', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('dataNascimento', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['tb_endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('tb_funcionario',
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('pessoa_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_funcionario')
    op.drop_table('tb_pessoa')
    op.drop_table('tb_endereco')
    # ### end Alembic commands ###
