"""empty message

Revision ID: b678ce1858e7
Revises: 70283c74e96f
Create Date: 2023-10-17 20:13:36.771951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b678ce1858e7'
down_revision = '70283c74e96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_observacoes_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_observacoes_educando_deficiencia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_deficiencia', ['deficiencia_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_observacoes_educando', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_observacoes_educando_deficiencia_id_fkey', 'tb_deficiencia', ['deficiencia_id'], ['id'])

    # ### end Alembic commands ###
