"""atualizando tabelas

Revision ID: c2f9b95c5159
Revises: 59a350053785
Create Date: 2023-09-17 22:08:10.392324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2f9b95c5159'
down_revision = '59a350053785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.alter_column('dataNascimento',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.alter_column('dataNascimento',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
