"""empty message

Revision ID: c3868695d7bf
Revises: 04d23503ddc8
Create Date: 2023-11-20 09:22:04.851311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3868695d7bf'
down_revision = '04d23503ddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
