"""empty message

Revision ID: cbd8b55eba01
Revises: a5d5cbd34cdd
Create Date: 2023-10-31 12:41:18.841941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd8b55eba01'
down_revision = 'a5d5cbd34cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_relatorio_academico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('educando_id', sa.UUID(), nullable=False),
    sa.Column('relatorio', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['educando_id'], ['tb_educando.pessoa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_relatorio_academico')
    # ### end Alembic commands ###
