"""empty message

Revision ID: da6c602d31f0
Revises: b678ce1858e7
Create Date: 2023-10-17 20:16:26.540049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6c602d31f0'
down_revision = 'b678ce1858e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint('tb_educando_observacoesEducando_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_educando', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_educando_observacoesEducando_id_fkey', 'tb_observacoes_educando', ['observacoesEducando_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
