"""atualizando tabelas

Revision ID: dbd399764abd
Revises: f08341abc5d5
Create Date: 2023-09-18 11:07:14.173438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd399764abd'
down_revision = 'f08341abc5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.create_unique_constraint(None, ['rg'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
