"""empty message

Revision ID: dc60c9491226
Revises: 843fc5fd64ba
Create Date: 2023-09-20 15:54:20.304358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc60c9491226'
down_revision = '843fc5fd64ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbFuncionario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('tbFuncionario_enderecoId_fkey', type_='foreignkey')
        batch_op.drop_column('enderecoId')

    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enderecoId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbEndereco', ['enderecoId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbPessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enderecoId')

    with op.batch_alter_table('tbFuncionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enderecoId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tbFuncionario_enderecoId_fkey', 'tbEndereco', ['enderecoId'], ['id'])
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
