"""adicionado comentario

Revision ID: e40cb6999b0a
Revises: 270583fbbd79
Create Date: 2023-12-10 01:15:17.830993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40cb6999b0a'
down_revision = '270583fbbd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_comentario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('dataCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['tb_funcionario.pessoa_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_comentario_relatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comentario_id', sa.UUID(), nullable=True),
    sa.Column('relatorio_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['comentario_id'], ['tb_comentario.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['tb_relatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_comentario_relatorio')
    op.drop_table('tb_comentario')
    # ### end Alembic commands ###
