"""empty message

Revision ID: e59fc2d7ef51
Revises: adbacc22f280
Create Date: 2023-10-16 08:13:40.355543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59fc2d7ef51'
down_revision = 'adbacc22f280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('bolsaFamilia_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('bolsaFamilia_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
