"""empty message

Revision ID: f30749d9cfad
Revises: 30dfdcbb5233
Create Date: 2023-10-31 13:38:09.903079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f30749d9cfad'
down_revision = '30dfdcbb5233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataEnvio', sa.DateTime(), nullable=True))
        batch_op.drop_column('dataCriacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_relatorio_academico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('dataEnvio')

    # ### end Alembic commands ###
