"""empty message

Revision ID: f4d6016cfa0c
Revises: 3419e645689e
Create Date: 2023-10-18 20:14:32.900596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d6016cfa0c'
down_revision = '3419e645689e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.drop_constraint('tb_pessoa_endereco_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_endereco', ['endereco_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_pessoa_endereco_id_fkey', 'tb_endereco', ['endereco_id'], ['id'])

    # ### end Alembic commands ###
